CREATE TABLE WORKSHEET (WORKSHEET_ID INT PRIMARY KEY, EMPLOYEE_ID INT NOT NULL, MONTH_VALUE varchar(50) NOT NULL);



CREATE TABLE WORKSHEET_DETAILS (WSDETAILS_ID INT PRIMARY KEY, WORKSHEET_ID INT REFERENCES WORKSHEET(WORKSHEET_ID), WORK_STATUS varchar(50) NOT NULL, NO_OF_HOURS INT DEFAULT 0, PROJECT_CODE INT NOT NULL, DATE DATE NOT NULL);